### ISSUE TITLE
🐛 [BUG]: ERROR TS2589 Type instantiation is excessively deep and possibly infinite.

### ISSUE THREAD

**Issue by throrin19** [bcakmakoglu/vue-flow#1886]
### Is there an existing issue for this?

- [x] I have searched the existing issues and this is a new bug.

### Current Behavior

Hello, I have a problem with vue-flow after upgrade from 1.44.0 to 1.45.0 with typescript.

I reproduce the example made here : https://vueflow.dev/examples/edges/connection-radius.html

But I have this error in my code : 

```
closest.node = closestNode.node; // ERROR TS2589 Type instantiation is excessively deep and possibly infinite.
```

### Expected Behavior

No error TS2589

### Steps To Reproduce

1. Create typescript project
2. Get code in the example https://vueflow.dev/examples/edges/connection-radius.html
3. You have error TS2589

### Relevant log output

```shell

```

### Anything else?

In previous version (1.44.0) there is no TS error for that.

**Comment by bcakmakoglu** [comment]
What does your code look like exactly?
The example wasn't written in TypeScript so it might be you didn't type things correctly.

This here should work:
```vue
<script lang="ts" setup>
import type { ConnectingHandle, EdgeProps, GraphNode, HandleElement } from '@vue-flow/core'
import { connectionExists, getBezierPath, useVueFlow } from '@vue-flow/core'
import { computed, reactive, shallowRef, watch } from 'vue'

const props = defineProps<EdgeProps>()

const { getNodes, connectionStartHandle, onConnectEnd, addEdges, edges } = useVueFlow()

const closest = reactive<{
  node: GraphNode | null
  handle: HandleElement | null
  startHandle: ConnectingHandle | null
}>({
  node: null,
  handle: null,
  startHandle: connectionStartHandle.value,
})

const canSnap = shallowRef(false)

const HIGHLIGHT_COLOR = '#f59e0b'

const SNAP_HIGHLIGHT_COLOR = '#10b981'

const MIN_DISTANCE = 75

const SNAP_DISTANCE = 30

watch([() => props.targetY, () => props.targetX], (_, __, onCleanup) => {
  const closestNode = getNodes.value.reduce(
    (res, n) => {
      if (n.id !== connectionStartHandle.value?.nodeId) {
        const dx = props.targetX - (n.computedPosition.x + n.dimensions.width / 2)
        const dy = props.targetY - (n.computedPosition.y + n.dimensions.height / 2)
        const d = Math.sqrt(dx * dx + dy * dy)

        if (d < res.distance && d < MIN_DISTANCE) {
          res.distance = d
          res.node = n
        }
      }

      return res
    },
    {
      distance: Number.MAX_VALUE,
      node: null,
    } as { distance: number; node: GraphNode | null },
  )

  if (!closestNode.node) {
    return
  }

  canSnap.value = closestNode.distance < SNAP_DISTANCE

  const type = connectionStartHandle.value?.type === 'source' ? 'target' : 'source'

  const closestHandle = closestNode.node.handleBounds[type]?.reduce((prev, curr) => {
    const prevDistance = Math.sqrt((prev.x - props.targetX) ** 2 + (prev.y - props.targetY) ** 2)
    const currDistance = Math.sqrt((curr.x - props.targetX) ** 2 + (curr.y - props.targetY) ** 2)

    return prevDistance < currDistance ? prev : curr
  })

  if (
    connectionStartHandle.value &&
    connectionExists(
      {
        source: connectionStartHandle.value.nodeId,
        sourceHandle: connectionStartHandle.value.id,
        target: closestNode.node.id,
        targetHandle: closestHandle?.id,
      },
      edges.value,
    )
  ) {
    return
  }

  if (closestHandle) {
    const el = document.querySelector(`[data-nodeid='${closestNode.node.id}']`) as HTMLDivElement

    const prevStyle = el.style.backgroundColor
    el.style.backgroundColor = canSnap.value ? SNAP_HIGHLIGHT_COLOR : HIGHLIGHT_COLOR
    closest.node = closestNode.node
    closest.handle = closestHandle

    onCleanup(() => {
      el.style.backgroundColor = prevStyle
      closest.node = null
      closest.handle = null
    })
  }
})

const path = computed(() => getBezierPath(props))

onConnectEnd(() => {
  if (closest.startHandle && closest.handle && closest.node) {
    if (canSnap.value) {
      addEdges([
        {
          sourceHandle: closest.startHandle.id,
          source: closest.startHandle.nodeId,
          target: closest.node.id,
          targetHandle: closest.handle.id,
        },
      ])
    }
  }
})

const strokeColor = computed(() => {
  if (canSnap.value) {
    return SNAP_HIGHLIGHT_COLOR
  }

  if (closest.node) {
    return HIGHLIGHT_COLOR
  }

  return '#222'
})
</script>

<template>
  <g>
    <path :d="path[0]" class="vue-flow__connection-path" />
    <circle :cx="props.targetX" :cy="props.targetY" fill="#fff" :stroke="strokeColor" :r="3" :stroke-width="1.5" />
  </g>
</template>
```

**Comment by throrin19** [comment]
I have same code but already the error on `closest.node = closestNode.node;` : 

```vue
<template>
    <g>
        <path
            :d="path[0]"
            class="vue-flow__connection-path" />
        <circle
            :cx="targetX"
            :cy="targetY"
            :r="4"
            :stroke="strokeColor"
            :stroke-width="1.5"
            fill="#fff" />
    </g>
</template>

<script setup lang="ts">
import type { ConnectingHandle, EdgeProps, GraphNode, HandleElement } from '@vue-flow/core';
import { connectionExists, getBezierPath, useVueFlow } from '@vue-flow/core';
import { computed, reactive, ref, watch } from 'vue';

const props = defineProps<Pick<EdgeProps, 'sourcePosition' | 'sourceX' | 'sourceY' | 'targetPosition' | 'targetX' | 'targetY'>>();

const {
    addEdges,
    connectionStartHandle,
    edges,
    getNodes,
    onConnectEnd,
} = useVueFlow();

/**
 * Toute cette partie est pour rendre magnétique la cible d'un lien
 * Trouvé dans les exemples : https://vueflow.dev/examples/edges/connection-radius.html
 */

const closest = reactive<{
    handle: HandleElement | null;
    node: GraphNode | null;
    startHandle: ConnectingHandle | null;
}>({
    handle: null as HandleElement | null,
    node: null as GraphNode | null,
    startHandle: connectionStartHandle.value,
});

const canSnap = ref(false);
const HIGHLIGHT_COLOR = '#f59e0b';
const SNAP_HIGHLIGHT_COLOR = '#10b981';
const MIN_DISTANCE = 75;
const SNAP_DISTANCE = 30;

watch([() => props.targetY, () => props.targetX], (_, __, onCleanup) => {
    if (!connectionStartHandle.value) {
        return;
    }

    const closestNode = getNodes.value.reduce(
        (res, n) => {
            if (n.id !== connectionStartHandle.value?.nodeId) {
                const dx = props.targetX - (n.computedPosition.x + n.dimensions.width / 2);
                const dy = props.targetY - (n.computedPosition.y + n.dimensions.height / 2);
                const d = Math.sqrt(dx * dx + dy * dy);

                if (d < res.distance && d < MIN_DISTANCE) {
                    res.distance = d;
                    res.node = n;
                }
            }

            return res;
        },
        {
            distance: Number.MAX_VALUE,
            node: null as GraphNode | null,
        } as { distance: number; node: GraphNode | null },
    );

    if (!closestNode.node) {
        return;
    }

    canSnap.value = closestNode.distance < SNAP_DISTANCE;

    const type = connectionStartHandle.value.type === 'source' ? 'target' : 'source';

    const closestHandle = closestNode.node.handleBounds[type]?.reduce((prev, curr) => {
        const prevDistance = Math.sqrt((prev.x - props.targetX) ** 2 + (prev.y - props.targetY) ** 2);
        const currDistance = Math.sqrt((curr.x - props.targetX) ** 2 + (curr.y - props.targetY) ** 2);

        return prevDistance < currDistance ? prev : curr;
    }, { x: 0, y: 0 } as HandleElement);

    if (!closestHandle) {
        return;
    }

    if (
        connectionExists(
            {
                source: connectionStartHandle.value.nodeId,
                sourceHandle: connectionStartHandle.value.id,
                target: closestNode.node.id,
                targetHandle: closestHandle.id,
            },
            edges.value,
        )
    ) {
        return;
    }

    if (closestHandle) {
        const el = document.querySelector<HTMLElement>(`[data-nodeid='${closestNode.node.id}']`);

        const prevStyle = el?.style?.backgroundColor;
        // eslint-disable-next-line ts/no-non-null-assertion
        el!.style!.backgroundColor = canSnap.value ? SNAP_HIGHLIGHT_COLOR : HIGHLIGHT_COLOR;
        closest.node = closestNode.node;
        closest.handle = closestHandle;

        onCleanup(() => {
            // eslint-disable-next-line ts/no-non-null-assertion
            el!.style!.backgroundColor = prevStyle as string;
            closest.node = null;
            closest.handle = null;
        });
    }
});

const path = computed(() => getBezierPath(props));

onConnectEnd(() => {
    if (closest.startHandle && closest.handle && closest.node) {
        if (canSnap.value) {
            addEdges([
                {
                    source: closest.startHandle.nodeId,
                    sourceHandle: closest.startHandle.id,
                    target: closest.node.id,
                    targetHandle: closest.handle.id,
                },
            ]);
        }
    }
});

const strokeColor = computed(() => {
    if (canSnap.value) {
        return SNAP_HIGHLIGHT_COLOR;
    }

    if (closest.node) {
        return HIGHLIGHT_COLOR;
    }

    return '#222';
});
</script>
```

**Comment by throrin19** [comment]
I'm on typescript 5.8.3 and vue-tsc 2.2.10.

But as I said, it works fine with vue-flow 1.44.0. The error appears in version 1.45.0

**Comment by bcakmakoglu** [comment]
Thanks, that helps reproducing the issue :)
I'll see if I can add a patch to fix this with the next release - for now, as a workaround, you should be able to just do this `closest.node = closestNode.node as any`
It's just a temporary workaround though until I published an actual fix for it.

**Comment by Hekikai** [comment]
Have the same problem after upgrade to 1.45.0

**Comment by Hekikai** [comment]
Thank you for the answer! Looking forward to solution 🙏🏻

**Comment by MingZeY** [comment]
// ERROR TS2589 Type instantiation is excessively deep and possibly infinite.
const filterd:Edge[] = edges.value.filter((e) => {
        if(e.target == connection.target && e.targetHandle == connection.targetHandle){
            return false;
        }
        return true;
    })

Also occurred in the official example code
https://vueflow.dev/guide/edge.html
function removeEdge(id) {
  edges.value = edges.value.filter((edge) => edge.id !== id)
}
